name: Filters

on:
 push:
  branches-ignore:
    - main
  branches:
    - feature-branch

jobs:
 filters:
  runs-on: ubuntu-latest
  steps:
   - run: echo "testing filters"
   - run: echo "testing successful"

   
