name: runner-context
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_VAR: 'jobs'
    steps:
      - uses: actions/checkout@v4
      - name: Build with logs
        run: |
          mkdir ${{ runner.temp }}/build_logs
          echo "Logs from building" > ${{ runner.temp }}/build_logs/build.logs
          exit 0
      - name: Upload logs on fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Build failure logs
          path: ${{ runner.temp }}/build_logs

  
  get-runner-info:
    runs-on: ubuntu-latest
    env:
      MY_VAR: 'steps'
    steps:
      - name: Display runner info
        # env: 
        # MY_VAR: 'steps'
        run: |
          echo "Runner name: ${{ runner.name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner temp: ${{ runner.temp }}"
          echo "Runner workspace: ${{ runner.workspace }}"

