name: runner-context
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with logs
        run: |
          mkdir ${{ runner.temp }}/build_logs
          echo "Logs from building" > ${{ runner.temp }}/build_logs/build.logs
          exit 0
      - name: Upload logs on fail
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Build failure logs
          path: ${{ runner.temp }}/build_logs

  
  get-runner-info:
    runs-on: ubuntu-latest
    env:
      MY_VAR: 'jobs'
    steps:
      - name: Display runner info
        env: 
        MY_VAR: 'steps'
        run: |
          echo "Runner name: ${{ runner.name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner temp: ${{ runner.temp }}"
          echo "Runner workspace: ${{ runner.workspace }}"
          echo "Runner group: ${{ runner.group }}"
          echo "Runner labels: ${{ runner.labels }}"
          echo "Runner version: ${{ runner.version }}"
          echo "Runner tools cache: ${{ runner.tools_cache }}"
          echo "Runner job workspace: ${{ runner.job_workspace }}"
          echo "Runner job id: ${{ runner.job_id }}"
          echo "Runner job name: ${{ runner.job_name }}"
          echo "Runner job status: ${{ runner.job_status }}"
          echo "Runner job url: ${{ runner.job_url }}"
