name: secret-context
on:
  workflow_dispatch

jobs:
  test-authentication:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Access and print a secret (for demonstration purposes, avoid printing secrets in real workflows)
      - name: Access GitHub Secret
        run: echo "The secret value is ${{ secrets.MY_SECRET }}"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      # Example of using a secret in a script
      - name: Use secret in a script
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "Secret is not set!"
            exit 1
          else
            echo "Using the secret securely."
          fi
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
