name: secret-context
on:
  workflow_dispatch
jobs:
  test-authentication:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
     - run |
       
        
  
    
  
  
  
