name: git-workshop
on: [push, pull_request]
# run-name: ${{github.actor}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # $GITHUB_WORKSPACE
    - name: checkout code
      uses: actions/checkout@v4.2.2
    - name: initialize npm
      run: npm init -y
    - name: install dependencies
      run: npm install
  #   - name: build-npm-action
  # # You may pin to the exact commit or the version.
  # # uses: ankitasen-ubmainz/build-npm-action@933de398871bd9906e82336d74c730ae222d6fbe
  #     uses: ankitasen-ubmainz/build-npm-action@v0.2
  #   - name: npm build
  #     run: npm run build   
          
  test:
    runs-on: ubuntu-latest
    steps:
    # $GITHUB_WORKSPACE
    - name: checkout
      uses: actions/checkout@v4.2.2
    - name: initialize npm
      run: npm init -y
    - name: install dependencies
      run: npm install
    # - name: Run Tests
    #   run: npm test
