name: git-workshop
on: [push, pull_request]
# run-name: ${{github.actor}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # $GITHUB_WORKSPACE
    - name: checkout code
      uses: actions/checkout@v4.2.2
    - name: install dependencies
      run: npm install
    - name: build project
      run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
    # $GITHUB_WORKSPACE
    - name: checkout
      uses: actions/checkout@v$.2.2
    - name: install dependencies
      run: npm install
    - name: Run Tests
      run: npm test
