name: git-workshop
on: [push, pull_request]
# run-name: ${{github.actor}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # $GITHUB_WORKSPACE
    - name: checkout
      uses: actions/checkout@v4.2.2
    - run: "building image"
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v$.2.2
    - run: " running test suites" 
